CREATE TABLE usuarios (
    usuario_id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    correo VARCHAR(255) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    pais VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    rango VARCHAR(50) DEFAULT 'OPERARIO NOVATO' NOT NULL,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

